on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy images or assets if any
        run: |
          mkdir build
          # Copy asset folders here if you use local image files
          # cp -r images build/ || true 

      - name: Compile Marp Slides to HTML
        uses: marp-team/marp-cli-action@v1
        with:
          args: index.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment